### 🟢 جلب جميع سجلات الاستعارة
GET http://localhost:8081/api/borrowing-records
Accept: application/json

### 🔴 استعارة كتاب جديد
POST http://localhost:8081/api/borrowing-records
Content-Type: application/json

{
  "bookId": 1,
  "patronId": 1
}

### 🔴 إرجاع كتاب مستعار
PUT http://localhost:8081/api/borrowing-records/return/1
Accept: application/json
